development: &default
  adapter: postgresql
  encoding: unicode
  database: hb-ws-development
  host: <%= ENV.fetch 'DB_HOST', '127.0.0.1' %>
  username: <%= ENV.fetch 'DB_USER', 'postgres' %>
  password: <%= ENV.fetch 'DB_PASSWD', 'postgres' %>

test:
  <<: *default
  database: hb-ws-test
